# personnaliser le site à votre marque en remplaçant
# nom_intuition par le nom de votre intuition
# mon_equipe par le nom de votre équipe
# 
intuition: insa'roule
nom_equipe: oubishoft
code_equipe: 1G

theme: jekyll-theme-dinky
